name: Snyk Infrastructure as Code and GitHub Security example
on: push
jobs:
  snyk:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run Snyk to check terraform configuration files for issues
      continue-on-error: true
      uses: snyk/actions/iac@master
      with:
        output: snyk.sarif
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
    - uses: github/codeql-action/upload-sarif@v1
      with:
        sarif_file: snyk.sarif
